// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package gencmd

import (
	"github.com/gofunct/gogen/pkg/cli"
	"github.com/gofunct/gogen/pkg/gogencmd"
)

// Injectors from wire.go:

func newApp(command *Command) (*App, error) {
	ctx := ProvideCtx(command)
	gogencmdCtx := ProvideGogenCtx(ctx)
	fs := gogencmd.ProvideFS(gogencmdCtx)
	io := gogencmd.ProvideIO(gogencmdCtx)
	ui := cli.UIInstance(io)
	rootDir := gogencmd.ProvideRootDir(gogencmdCtx)
	fileSystem := ProvideTemplateFS(command)
	shouldRunFunc := ProvideShouldRun(command)
	generator := NewGenerator(fs, ui, rootDir, fileSystem, shouldRunFunc)
	app := &App{
		Generator: generator,
		UI:        ui,
	}
	return app, nil
}
