// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/gofunct/common/bingen/tool"
	"github.com/gofunct/gogen/pkg/cli"
	"github.com/gofunct/gogen/pkg/excmd"
	"github.com/gofunct/gogen/grapicmd"
	"github.com/gofunct/gogen/pkg/gogencmdinternal/module"
	"github.com/gofunct/gogen/pkg/gogencmdinternal/usecase"
	"github.com/gofunct/gogen/protoc"
)

// Injectors from wire.go:

func NewUI(ctx *grapicmd.Ctx) cli.UI {
	io := grapicmd.ProvideIO(ctx)
	ui := cli.UIInstance(io)
	return ui
}

func NewCommandExecutor(ctx *grapicmd.Ctx) excmd.Executor {
	io := grapicmd.ProvideIO(ctx)
	executor := excmd.NewExecutor(io)
	return executor
}

func NewGenerator(ctx *grapicmd.Ctx) module.Generator {
	io := grapicmd.ProvideIO(ctx)
	ui := cli.UIInstance(io)
	generator := ProvideGenerator(ctx, ui)
	return generator
}

func NewScriptLoader(ctx *grapicmd.Ctx) module.ScriptLoader {
	io := grapicmd.ProvideIO(ctx)
	executor := excmd.NewExecutor(io)
	scriptLoader := ProvideScriptLoader(ctx, executor)
	return scriptLoader
}

func NewToolRepository(ctx *grapicmd.Ctx) (tool.Repository, error) {
	fs := grapicmd.ProvideFS(ctx)
	execInterface := grapicmd.ProvideExecer(ctx)
	io := grapicmd.ProvideIO(ctx)
	rootDir := grapicmd.ProvideRootDir(ctx)
	config := protoc.ProvideGexConfig(fs, execInterface, io, rootDir)
	repository, err := protoc.ProvideToolRepository(config)
	if err != nil {
		return nil, err
	}
	return repository, nil
}

func NewProtocWrapper(ctx *grapicmd.Ctx) (protoc.Wrapper, error) {
	config := grapicmd.ProvideProtocConfig(ctx)
	fs := grapicmd.ProvideFS(ctx)
	execInterface := grapicmd.ProvideExecer(ctx)
	io := grapicmd.ProvideIO(ctx)
	ui := cli.UIInstance(io)
	rootDir := grapicmd.ProvideRootDir(ctx)
	gexConfig := protoc.ProvideGexConfig(fs, execInterface, io, rootDir)
	repository, err := protoc.ProvideToolRepository(gexConfig)
	if err != nil {
		return nil, err
	}
	wrapper := protoc.NewWrapper(config, fs, execInterface, ui, repository, rootDir)
	return wrapper, nil
}

func NewInitializeProjectUsecase(ctx *grapicmd.Ctx) usecase.InitializeProjectUsecase {
	fs := grapicmd.ProvideFS(ctx)
	execInterface := grapicmd.ProvideExecer(ctx)
	io := grapicmd.ProvideIO(ctx)
	rootDir := grapicmd.ProvideRootDir(ctx)
	config := protoc.ProvideGexConfig(fs, execInterface, io, rootDir)
	ui := cli.UIInstance(io)
	generator := ProvideGenerator(ctx, ui)
	initializeProjectUsecase := ProvideInitializeProjectUsecase(ctx, config, ui, generator)
	return initializeProjectUsecase
}
